---
# tasks file for auditd

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install requirements
  ansible.builtin.package:
    name: bash
    state: present

- name: Install audit
  ansible.builtin.package:
    name: "{{ auditd_packages }}"
    state: present

- name: Configure auditd
  ansible.builtin.template:
    src: "{{ auditd_config_file }}.j2"
    dest: "{{ auditd_config_directory }}/{{ auditd_config_file }}"
    mode: "0640"
  notify:
    - Restart auditd

- name: Create rules.d directory
  ansible.builtin.file:
    path: "{{ auditd_config_directory }}/rules.d"
    state: directory
    mode: "0750"

- name: Place custom.rules
  ansible.builtin.template:
    src: custom.rules.j2
    dest: "{{ auditd_config_directory }}/rules.d/custom.rules"
    mode: "0664"
  notify:
    - Run augenrules
  when:
    - auditd_manage_rules

- name: Configure syslog plugin for auditd
  community.general.ini_file:
    path: "{{ auditd_config_directory }}/plugins.d/syslog.conf"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: '0640'
    state: present
  loop: "{{ auditd_plugin_syslog | dict2items }}"
  when: auditd_plugin_syslog is defined

- name: Create a Seperate Journald Context for auditd
  when: auditd_journal_context is true
  block:
    - name: Create auditd Journal Context
      ansible.builtin.template:
        src: journald@audit.conf.j2
        dest: /etc/systemd/journald@audit.conf
        mode: "0644"
      notify:
        - Restart systemd-journald

    - name: Restart Journald to Activate the New Context
      ansible.builtin.meta: flush_handlers

- name: Configure systemd overrides
  when: auditd_journal_context is true
  ansible.builtin.include_tasks:
    file: systemd_overrides.yml
  loop:
    - auditd.service
    - systemd-journald-audit.socket
    - systemd-journald@audit.service
    - systemd-journald.service

- name: Remove the systemd-journald-auditd.socket from systemd-journald.service
  community.general.ini_file:
    path: /etc/systemd/system/systemd-journald.service
    section: Service
    option: Sockets
    value: "journald.socket systemd-journald-dev-log.socket"
    mode: "0644"
    exclusive: true
    state: present
    no_extra_spaces: true
  notify:
    - Restart systemd-journald

- name: Add systemd-journald@audit.service to systemd-journald-audit.socket
  community.general.ini_file:
    path: /etc/systemd/system/systemd-journald-audit.socket
    section: Socket
    option: Service
    value: systemd-journald@audit.service
    mode: "0644"
    exclusive: true
    state: present
    no_extra_spaces: true
  notify:
    - Restart systemd-journald-audit.socket
    - Restart systemd-journald@audit.service

- name: Add systemd-journald-audit.socket to systemd-journald@audit.service
  community.general.ini_file:
    path: /etc/systemd/system/systemd-journald@audit.service
    section: Service
    option: Sockets
    value: "systemd-journald@%i.socket systemd-journald-audit.socket"
    mode: "0644"
    exclusive: true
    no_extra_spaces: true
  notify:
    - Restart systemd-journald@audit.service

- name: Add systemd-journald-audit.socket to systemd-journald@audit.service Requires
  community.general.ini_file:
    path: /etc/systemd/system/systemd-journald@audit.service
    section: Unit
    option: Requires
    value: "systemd-journald@%i.socket systemd-journald-varlink@%i.socket systemd-journald-audit.socket"
    mode: "0644"
    exclusive: true
    no_extra_spaces: true
  notify:
    - Restart systemd-journald@audit.service

- name: Add systemd-journald-audit.socket to systemd-journald@audit.service After
  community.general.ini_file:
    path: /etc/systemd/system/systemd-journald@audit.service
    section: Unit
    option: After
    value: "systemd-journald@%i.socket systemd-journald-varlink@%i.socket systemd-journald-audit.socket"
    mode: "0644"
    exclusive: true
    no_extra_spaces: true
  notify:
    - Restart systemd-journald@audit.service

- name: Configure the Logging Context
  community.general.ini_file:
    path: /etc/systemd/system/auditd.service
    section: Service
    option: LogNamespace
    value: audit
    mode: "0644"
    no_extra_spaces: true
  notify:
    - Restart auditd

- name: Restart any services that were notified
  ansible.builtin.meta: flush_handlers

- name: Start and enable systemd-journald@audit
  ansible.builtin.service:
    name: "systemd-journald@audit"
    state: started
    enabled: true
  when:
    - auditd_start_service
    - auditd_journal_context is true

- name: Start and enable auditd
  ansible.builtin.service:
    name: "{{ auditd_service }}"
    state: started
    enabled: true
  when:
    - auditd_start_service
