---
# handlers file for auditd

- name: Run augenrules
  ansible.builtin.command:
    cmd: augenrules
  changed_when: true
  notify:
    - Load rules

- name: Load rules
  ansible.builtin.command:
    cmd: augenrules --load
  changed_when: true
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]

- name: Restart auditd
  ansible.builtin.service:
    name: "{{ auditd_service }}"
    state: restarted
  when:
    - auditd_start_service

- name: Restart systemd-journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
    daemon_reload: true

- name: Restart systemd-journald@audit.service
  ansible.builtin.systemd_service:
    name: systemd-journald@audit.service
    state: restarted
    daemon_reload: true

- name: Restart systemd-journald-audit.socket
  ansible.builtin.systemd_service:
    name: systemd-journald-audit.socket
    state: restarted
    daemon_reload: true
